[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string]$PharmaceuticalSource,
    [Parameter(Mandatory)] [string]$OptimizationsSource,
    [Parameter(Mandatory)] [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

function Get-FrameworkPackages([string]$Source, [string]$Version) {
    $packages = @(Get-ChildItem -LiteralPath $Source -Directory -Filter "*-global-framework-$Version")
    if ($packages.Count -ne 4) { throw "Expected four *-global-framework-$Version packages in $Source; found $($packages.Count)." }
    return $packages
}

function Get-SpecialistAlias([string]$ScriptPath, [string]$SpecialistId) {
    $content = Get-Content -LiteralPath $ScriptPath -Raw
    foreach ($candidate in [regex]::Matches($content, '(?s)\[Alias\((?<aliases>.*?)\)\]\s*\[switch\]\s*\$\w+')) {
        $aliases = [regex]::Matches($candidate.Groups['aliases'].Value, '"(?<value>[^"]+)"') | ForEach-Object { $_.Groups['value'].Value }
        $expected = "with-$SpecialistId"
        if ($aliases -contains $expected) { return $expected }
    }
    throw "No -with-$SpecialistId alias found in $ScriptPath."
}

function Copy-Package([string]$Source, [string]$Destination) {
    Copy-Item -LiteralPath $Source -Destination $Destination -Recurse -Force
}

function Set-IniValue([string]$Path, [string]$Section, [string]$Key, [string]$Value) {
    if ($script:writtenSections.Add($Section)) { Add-Content -LiteralPath $Path -Value "[$Section]" }
    Add-Content -LiteralPath $Path -Value "$Key=$Value"
}

$products = @(
    @{ Id = 'farmaceuticos'; Title = 'Agentes Farmacêuticos'; Version = 'v1'; Source = $PharmaceuticalSource },
    @{ Id = 'otimizacoes'; Title = 'Otimizações IA'; Version = 'v5'; Source = $OptimizationsSource }
)

Remove-Item -LiteralPath $OutputPath -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path $OutputPath | Out-Null
$catalog = Join-Path $OutputPath 'catalog.ini'
Set-Content -LiteralPath $catalog -Value '; Generated by Prepare-Payload.ps1. Do not edit.' -Encoding utf8
$script:writtenSections = [System.Collections.Generic.HashSet[string]]::new()
Add-Content -LiteralPath $catalog -Value '[products]'
Add-Content -LiteralPath $catalog -Value ('ids=' + ($products.Id -join ','))

foreach ($product in $products) {
    $source = [IO.Path]::GetFullPath($product.Source)
    $packages = Get-FrameworkPackages $source $product.Version
    $platformIds = @()
    foreach ($package in $packages) {
        $platform = $package.Name -replace "-global-framework-$($product.Version)$", ''
        $platformIds += $platform
        $destination = Join-Path $OutputPath (Join-Path $product.Id $package.Name)
        New-Item -ItemType Directory -Path (Split-Path -Parent $destination) -Force | Out-Null
        Copy-Package $package.FullName $destination

        $scriptPath = Join-Path $package.FullName 'scripts/install.ps1'
        if (-not (Test-Path -LiteralPath $scriptPath -PathType Leaf)) { throw "Windows installer missing: $scriptPath" }
        $specialists = @()
        $optional = Join-Path $package.FullName 'optional'
        if (Test-Path -LiteralPath $optional -PathType Container) {
            foreach ($item in Get-ChildItem -LiteralPath $optional -Directory | Sort-Object Name) {
                $specialists += $item.Name
                Set-IniValue $catalog "specialist.$($product.Id).$platform.$($item.Name)" 'name' $item.Name
                Set-IniValue $catalog "specialist.$($product.Id).$platform.$($item.Name)" 'alias' (Get-SpecialistAlias $scriptPath $item.Name)
            }
        }
        Add-Content -LiteralPath $catalog -Value "[product.$($product.Id).platform.$platform]"
        Add-Content -LiteralPath $catalog -Value "display=$platform"
        Add-Content -LiteralPath $catalog -Value "package=$($product.Id)/$($package.Name)"
        Add-Content -LiteralPath $catalog -Value ('specialists=' + ($specialists -join ','))
    }
    Add-Content -LiteralPath $catalog -Value "[product.$($product.Id)]"
    Add-Content -LiteralPath $catalog -Value "title=$($product.Title)"
    Add-Content -LiteralPath $catalog -Value "version=$($product.Version)"
    Add-Content -LiteralPath $catalog -Value ('platforms=' + ($platformIds -join ','))
}

Write-Host "Payload prepared at $OutputPath"
